---
defaults:
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: smart
      strict_method: rebase

pull_request_rules:
  - name: remove outdated approvals
    conditions:
      - base~=^(main)|(release-.+)$
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
  - name: automatic merge
    conditions:
      - base~=^(main)|(release-.+)$
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
    actions:
      merge: {}
      dismiss_reviews: {}
      delete_head_branch: {}
